[project]
name = "python-ai-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Unnayan-Singh", email = "unnayansingh2005@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.142.4",
    "google-genai>=2.29.0",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
    "streamlit>=1.65.0",
]

[project.scripts]
python-ai-project = "python_ai_project:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
